OMCPortal/Controllers/OMCController.cs
using System;
using System.Web.Mvc;
using OMCPortal.Models;

namespace OMCPortal.Controllers
{
    public class OMCController : Controller
    {
        string version = "1.0.0.7 Beta";
        OMCInstances instances = new OMCInstances();

        public ActionResult Index()
        {
            if (Session["Logged"] == null)
                return RedirectToAction("Login");
            ViewBag.version = version;
            return View();
        }

        public ActionResult Dashboard()
        {
            if (Session["Logged"] == null)
                return RedirectToAction("Login");
            instances.Refresh();
            ViewBag.data = instances.instances;
            ViewBag.version = version;
            return View();
        }

        public ActionResult Details( int id )
        {
            if (Session["Logged"] == null)
                return RedirectToAction("Login");
            ViewBag.data = null;
            ViewBag.version = version;
            instances.Refresh();
            if (id != -1)
            {
                foreach (var item in instances.instances)
                {
                    if (item == null)
                        continue;
                    if (item.InstanceID == id)
                    {
                        ViewBag.data = item;
                        break;
                    }
                }
            }
            return View();
        }

        public ActionResult LastErrors(int id)
        {
            if (Session["Logged"] == null)
                return RedirectToAction("Login");
            instances.ReloadErrors(id);
            instances.Refresh();
            ViewBag.data = instances.errors;
            ViewBag.sitecd = instances.SiteCD(id);
            ViewBag.version = version;
            return View();
        }

        public ActionResult LastMessages(int id)
        {
            if (Session["Logged"] == null)
                return RedirectToAction("Login");
            instances.ReloadMessages(id);
            instances.Refresh();            
            ViewBag.data = instances.messages;
            ViewBag.sitecd = instances.SiteCD(id);
            ViewBag.version = version;
            return View();
        }

        [HttpPost]
        public JsonResult Refresh()
        {
            if (Session["Logged"] == null)
                return null;
            instances.Refresh();
            JsonResult result = Json(instances.instances, JsonRequestBehavior.AllowGet);
            return result;
        }

        public ActionResult History( int id )
        {
            if (Session["Logged"] == null)
                return RedirectToAction("Login");
            instances.ReloadHistory(id);
            ViewBag.data = instances.instancesHistory;
            ViewBag.sitecd = instances.SiteCD(id);
            ViewBag.version = version;
            return View();
        }

        public ActionResult Orders(int id)
        {
            if (Session["Logged"] == null)
                return RedirectToAction("Login");
            DateTime dt = DateTime.Now;
            String siteCD = instances.SiteCD(id);
            instances.ReloadOrders(siteCD, dt);
            ViewBag.data = instances.orders;
            ViewBag.sitecd = siteCD;
            ViewBag.version = version;
            ViewBag.year = dt.Year;
            ViewBag.month = dt.Month;
            ViewBag.day = dt.Day;
            return View();
        }

        public ActionResult Login()
        {
            ViewBag.version = version;
            return View();
        }

        public ActionResult Logout()
        {
            Session["Logged"] = null;
            Session["UserName"] = null;
            return RedirectToAction("Login");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Login(OMCLoginModel objUser)
        {
            if (ModelState.IsValid)
            {
                if (objUser.LoginOK())
                {
                    Session["UserName"] = objUser.UserName;
                    Session["Logged"] = "TRUE";
                    return RedirectToAction("Dashboard");
                }
                else
                    return RedirectToAction("Login");
            }
            return View(objUser);
        }

        [HttpPost]
        public JsonResult LoadOrders(String siteCD, String year, String month, String day)
        {
            if( String.IsNullOrEmpty(year) || String.IsNullOrEmpty(month) || String.IsNullOrEmpty(day) || String.IsNullOrEmpty(siteCD))            
                return Json(null, JsonRequestBehavior.AllowGet);
            DateTime dt = new DateTime(Convert.ToInt32(year), Convert.ToInt32(month), Convert.ToInt32(day));
            instances.ReloadOrders(siteCD, dt);
            JsonResult result = Json(instances.orders, JsonRequestBehavior.AllowGet);
            String str = result.ToString();
            return result;
        }

        [HttpPost]
        public JsonResult FindOrder(String siteCD, String dms_ident)
        {
            if (String.IsNullOrEmpty(dms_ident) || String.IsNullOrEmpty(siteCD))
                return Json(null, JsonRequestBehavior.AllowGet);
            instances.FindOrder(siteCD, dms_ident);
            JsonResult result = Json(instances.orders, JsonRequestBehavior.AllowGet);
            String str = result.ToString();
            return result;
        }

    }
}

OMCPortal/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <title>@ViewBag.Title - WingsOMC Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

    <!-- Bootstrap CSS CDN -->
    <link rel="stylesheet" href="~/Content/bootstrap.min.css">
    <link rel="stylesheet" href="~/Content/style5.css">

    <!-- Font Awesome JS -->
    <script defer src="https://use.fontawesome.com/releases/v5.0.13/js/solid.js" integrity="sha384-tzzSw1/Vo+0N5UhStP3bvwWPq+uvzCMfrN1fEFe+xBmv1C/AtVX5K0uZtmcHitFZ" crossorigin="anonymous"></script>
    <script defer src="https://use.fontawesome.com/releases/v5.0.13/js/fontawesome.js" integrity="sha384-6OIrr52G08NpOFSZdxxz1xdNSndlD4vdcf/q2myIUVO0VsqaGHJsB0RaBE01VTOY" crossorigin="anonymous"></script>
</head>
<body>
    <div id="wrapper" class="toggled">
    <div class="wrapper">
        <nav id="sidebar">
            <div class="sidebar-header">
                <h3>WingsSystems OMC</h3>
            </div>
            <ul class="list-unstyled components">
                <li class="active">
                    @Html.ActionLink("Home", "Index", "OMC", new { area = "" }, new { @class = "navbar-brand" })
                    <br />
                    <br />
                    <br />
                </li>
                <li>
                    @Html.ActionLink("Dashboard", "Dashboard", "OMC")
                </li>
                <li>
                    @Html.ActionLink("Logout", "Logout", "OMC")
                </li>
            </ul>
            <ul class="list-unstyled components">
                <li>
                    <a href="#pageSubmenu" data-toggle="collapse" aria-expanded="false" class="dropdown-toggle">Groups</a>
                    <ul class="collapse list-unstyled" id="pageSubmenu">
                        <li>
                            <a href="#">Group1</a>
                        </li>
                        <li>
                            <a href="#">Group2</a>
                        </li>
                        <li>
                            <a href="#">Group3</a>
                        </li>
                    </ul>
                </li>
            </ul>
            <br />
</nav>
        <div class="container-fluid" id="content" style="padding-top: 0px">
            <nav class="navbar" style="padding-top: 0px">
                <div class="container-fluid">
                    <button type="button" id="sidebarCollapse" class="navbar-btn">
                        <span></span>
                        <span></span>
                        <span></span>                        
                    </button>
                    <button class="btn btn-dark d-inline-block d-lg-none ml-auto" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                        <i class="fas fa-align-justify"></i>
                    </button>
                    @if (ViewBag.version != null)
                    {
                        <p align="center">Version: @ViewBag.version</p>
                    }
                    @if (Session["UserName"] == null)
                    {
                        <p align="center">Logged as: -</p>
                    }
                    else
                    {
                        <p align="center">Logged as: @Session["UserName"]</p>
                    }
                    <div class="collapse navbar-collapse" id="navbarSupportedContent">
                                              <ul class="nav navbar-nav ml-auto">
                                                    <!--  <li class="nav-item active">
                                                       <div>Logged as:</div>
                                                    </li>
                                                    <li class="nav-item">
                                                        <a class="nav-link" href="#">Page</a>
                                                    </li>
                                                    <li class="nav-item">
                                                        <a class="nav-link" href="#">Page</a>
                                                    </li>
                                                    <li class="nav-item">
                                                        <a class="nav-link" href="#">Page</a>
                                                    </li>-->
                                                </ul>
                    </div>
                </div>
            </nav>
            @RenderBody()
            <hr />
        </div>
        @Scripts.Render("~/bundles/jquery")
        @Scripts.Render("~/bundles/bootstrap")
        @RenderSection("scripts", required: false)

        <script type="text/javascript">
            $(document).ready(function () {
                $('#sidebarCollapse').on('click', function () {
                    $('#sidebar').toggleClass('active');
                    $(this).toggleClass('active');
                });
            });
            $(document).ready(function () {
                var height1 = $('.content').height()
                var height2 = $('body').height()

                if (height1 > height2) {
                    $('.sidebar').height(height1)
                } else {
                    $('.sidebar').height(height2)
                }
            });
        </script>
    </div>
    </div>
</body>
</html>